# PySNMP SMI module. Autogenerated from smidump -f python SMOKE-MIB
# by libsmi2pysnmp-0.1.3 at Thu Jul 18 15:01:22 2013,
# Python version sys.version_info(major=2, minor=7, micro=3, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( Bits, Integer32, Integer32, ModuleIdentity, MibIdentifier, NotificationType, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, enterprises, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "Integer32", "ModuleIdentity", "MibIdentifier", "NotificationType", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "enterprises")

# Objects

metraTech = MibIdentifier((1, 3, 6, 1, 4, 1))
smokeStatus = MibScalar((1, 3, 6, 1, 4, 1, 1), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: smokeStatus.setDescription("Smoke Test Machine Status")
smokeDescription = MibScalar((1, 3, 6, 1, 4, 1, 2), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: smokeDescription.setDescription("Status Description")
smokeMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 42)).setRevisions(("2013-07-18 12:00",))
if mibBuilder.loadTexts: smokeMIB.setOrganization("MetraTech")
if mibBuilder.loadTexts: smokeMIB.setContactInfo("Internet: http://metratech.com")
if mibBuilder.loadTexts: smokeMIB.setDescription("This Mib Module is used for MetraNet Smoke-Tests.")

# Augmentions

# Notifications

smokeTestTrap = NotificationType((1, 3, 6, 1, 4, 1, 3)).setObjects(*() )
if mibBuilder.loadTexts: smokeTestTrap.setDescription("Smoke Test Failure")

# Exports

# Module identity
mibBuilder.exportSymbols("SMOKE-MIB", PYSNMP_MODULE_ID=smokeMIB)

# Objects
mibBuilder.exportSymbols("SMOKE-MIB", metraTech=metraTech, smokeStatus=smokeStatus, smokeDescription=smokeDescription, smokeMIB=smokeMIB)

# Notifications
mibBuilder.exportSymbols("SMOKE-MIB", smokeTestTrap=smokeTestTrap)

